# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Cupcake"
license = "MIT"
licenselink = "https://github.com/han1475/cupcake/blob/master/LICENSE"
description = "A lightweight theme for hugo"
homepage = "https://han1475.com/"
tags = ["responsive","blog","lightweight"]
features = ["responsive","blog","lightweight"]
min_version = "0.41.0"

[author]
  name = "han1475"
  homepage = "https://han1475.com"
